"""Maintainer tool: write requirements.lock from the working shared venv, with the sha256 of every file PyPI has for
each pinned version (wheels for all platforms + sdist), so `pip install --require-hashes -r requirements.lock` works on
macOS and Linux alike. Run after a deliberate upgrade:  ~/.cache/motion-film/venv/bin/python scripts/lock_deps.py"""
import json, os, subprocess, sys, urllib.request
here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
frozen = subprocess.run([sys.executable, '-m', 'pip', 'freeze', '--exclude-editable'], capture_output=True, text=True, check=True).stdout.split()
out = ['# Generated by scripts/lock_deps.py from a working toolchain. Install: pip install --require-hashes -r requirements.lock', '']
for req in sorted(frozen, key=str.lower):
    name, ver = req.split('==')
    data = json.load(urllib.request.urlopen(f'https://pypi.org/pypi/{name}/{ver}/json', timeout=30))
    hashes = sorted({f['digests']['sha256'] for f in data['urls']})
    out.append(f'{name}=={ver} \\\n' + ' \\\n'.join(f'    --hash=sha256:{h}' for h in hashes))
open(os.path.join(here, 'requirements.lock'), 'w').write('\n'.join(out) + '\n')
print(len(frozen), 'packages locked')
